Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 100
Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - linters.gemspec
